CREATE DATABASE PETSHOP;

USE PETSHOP;

CREATE TABLE EMPRESA_MEDICAMENTO (
    IDMEDICAMENTO  SERIAL PRIMARY KEY,
    NOME           VARCHAR(100),
    NOME_TECNICO   VARCHAR(100),
    APLICACAO      VARCHAR(100),
    OBS            BLOB 
);

CREATE TABLE EMPRESA_TOSA (
    IDTOSA  SERIAL PRIMARY KEY,
    NOME    VARCHAR(100),
    OBS     BLOB  
);

CREATE TABLE EMPRESA_UF (
    IDUF  SERIAL PRIMARY KEY,
    NOME  VARCHAR(30),
    UF    VARCHAR(2)
);

CREATE TABLE SISTEMA_USUARIO (
    IDUSUARIO  SERIAL PRIMARY KEY,
    NOME       VARCHAR(20),
    SENHA      VARCHAR(10)
);

CREATE TABLE EMPRESA_ESPECIE (
    IDESPECIE  SERIAL PRIMARY KEY,
    NOME       VARCHAR(100),
    SIGLA      VARCHAR(4)
);

CREATE TABLE EMPRESA_RACA (
    IDRACA     SERIAL PRIMARY KEY,
    NOME       VARCHAR(100),
    IDESPECIE  BIGINT UNSIGNED NOT NULL,
    FOREIGN KEY (IDESPECIE) REFERENCES EMPRESA_ESPECIE (IDESPECIE) ON UPDATE CASCADE
);

CREATE TABLE EMPRESA_MUNICIPIO (
    IDMUNICIPIO  SERIAL PRIMARY KEY,
    NOME         VARCHAR(100),
    IDUF         BIGINT UNSIGNED NOT NULL,
    FOREIGN KEY (IDUF) REFERENCES EMPRESA_UF (IDUF) ON UPDATE CASCADE
);

CREATE TABLE SISTEMA_EMPRESA_CADASTRO (
    ID           SERIAL PRIMARY KEY,
    NOME         VARCHAR(100),
    APELIDO      VARCHAR(100),
    CNPJ         VARCHAR (14),
    LOGRADOURO   VARCHAR(100),
    BAIRRO       VARCHAR(50),
    IDMUNICIPIO  BIGINT UNSIGNED NOT NULL,
    TELEFONE1    VARCHAR(10),
    TELEFONE2    VARCHAR(10),
    FOREIGN KEY (IDMUNICIPIO) REFERENCES EMPRESA_MUNICIPIO (IDMUNICIPIO) ON UPDATE CASCADE
);

CREATE TABLE EMPRESA_CONTA (
    IDCONTA        SERIAL PRIMARY KEY,
    NOME           VARCHAR(100),
    APELIDO        VARCHAR(100),
    CNPJ           VARCHAR (14),
    CPF            VARCHAR (11),
    RG             VARCHAR (14),
    LOGRADOURO     VARCHAR(100),
    BAIRRO         VARCHAR(50),
    IDMUNICIPIO    BIGINT UNSIGNED NOT NULL,
    DATA_CADASTRO  DATE,
    TELEFONE1      VARCHAR(10),
    TELEFONE2      VARCHAR(10),
    OBS            BLOB  ,
    TIPO           VARCHAR(1),
    CRMV           VARCHAR(20),
    FOREIGN KEY (IDMUNICIPIO) REFERENCES EMPRESA_MUNICIPIO (IDMUNICIPIO) ON UPDATE CASCADE
);

CREATE TABLE EMPRESA_ANIMAL (
    IDANIMAL         SERIAL PRIMARY KEY,
    NOME             VARCHAR(100),
    IDCONTA          BIGINT UNSIGNED NOT NULL,
    DATA_NASCIMENTO  DATE,
    IDRACA           BIGINT UNSIGNED NOT NULL,
    COR1             VARCHAR(50),
    COR2             VARCHAR(50),
    PELAGEM          VARCHAR(100),
    OBS              BLOB  ,
    DATA_CADASTRO    DATE,
    FOREIGN KEY (IDCONTA) REFERENCES EMPRESA_CONTA (IDCONTA) ON UPDATE CASCADE,
    FOREIGN KEY (IDRACA) REFERENCES EMPRESA_RACA (IDRACA) ON UPDATE CASCADE
);

CREATE TABLE EMPRESA_RECEITUARIO (
    IDRECEITUARIO  SERIAL PRIMARY KEY,
    IDCONTA        BIGINT UNSIGNED NOT NULL,
    IDANIMAL       BIGINT UNSIGNED NOT NULL,
    DATA           DATE,
    FOREIGN KEY (IDCONTA) REFERENCES EMPRESA_CONTA (IDCONTA) ON UPDATE CASCADE,
	FOREIGN KEY (IDANIMAL) REFERENCES EMPRESA_ANIMAL (IDANIMAL) ON UPDATE CASCADE
);

CREATE TABLE EMPRESA_RECEITUARIO_PROD (
    IDRECEITUARIO_PROD  SERIAL PRIMARY KEY,
    IDRECEITUARIO       BIGINT UNSIGNED NOT NULL,
    IDMEDICAMENTO       BIGINT UNSIGNED NOT NULL,
    QTD                 DECIMAL(10,2),
    UNIDADE             VARCHAR(20),
    FOREIGN KEY (IDRECEITUARIO) REFERENCES EMPRESA_RECEITUARIO (IDRECEITUARIO) ON UPDATE CASCADE,
	FOREIGN KEY (IDMEDICAMENTO) REFERENCES EMPRESA_MEDICAMENTO (IDMEDICAMENTO) ON UPDATE CASCADE
);